Traceback (most recent call last):
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/emarshall/miniconda3/envs/mynewbook/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
image_pair1 = xr.open_dataset(velocity_pairs_ls[0]['url'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/file_manager.py:199[0m, in [0;36mCachingFileManager._acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    198[0m [38;5;28;01mtry[39;00m:
[0;32m--> 199[0m     file [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cache[49m[43m[[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_key[49m[43m][49m
[1;32m    200[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/lru_cache.py:53[0m, in [0;36mLRUCache.__getitem__[0;34m(self, key)[0m
[1;32m     52[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_lock:
[0;32m---> 53[0m     value [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cache[49m[43m[[49m[43mkey[49m[43m][49m
[1;32m     54[0m     [38;5;28mself[39m[38;5;241m.[39m_cache[38;5;241m.[39mmove_to_end(key)

[0;31mKeyError[0m: [<function _open_scipy_netcdf at 0x158ef40d0>, ('http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_image_pair/landsat/v02/N20E080/LC08_L1TP_142040_20191228_20200824_02_T1_X_LC08_L1TP_142040_20200113_20200823_02_T1_G0120V02_P098.nc',), 'r', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m image_pair1 [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[43mvelocity_pairs_ls[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43murl[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/api.py:495[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)[0m
[1;32m    483[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    484[0m     decode_cf,
[1;32m    485[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    491[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    492[0m )
[1;32m    494[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 495[0m backend_ds [38;5;241m=[39m [43mbackend[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m    496[0m [43m    [49m[43mfilename_or_obj[49m[43m,[49m
[1;32m    497[0m [43m    [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m    498[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mdecoders[49m[43m,[49m
[1;32m    499[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    500[0m [43m[49m[43m)[49m
[1;32m    501[0m ds [38;5;241m=[39m _dataset_from_backend_dataset(
[1;32m    502[0m     backend_ds,
[1;32m    503[0m     filename_or_obj,
[0;32m   (...)[0m
[1;32m    510[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    511[0m )
[1;32m    512[0m [38;5;28;01mreturn[39;00m ds

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/scipy_.py:282[0m, in [0;36mScipyBackendEntrypoint.open_dataset[0;34m(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, mode, format, group, mmap, lock)[0m
[1;32m    280[0m store_entrypoint [38;5;241m=[39m StoreBackendEntrypoint()
[1;32m    281[0m [38;5;28;01mwith[39;00m close_on_error(store):
[0;32m--> 282[0m     ds [38;5;241m=[39m [43mstore_entrypoint[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m    283[0m [43m        [49m[43mstore[49m[43m,[49m
[1;32m    284[0m [43m        [49m[43mmask_and_scale[49m[38;5;241;43m=[39;49m[43mmask_and_scale[49m[43m,[49m
[1;32m    285[0m [43m        [49m[43mdecode_times[49m[38;5;241;43m=[39;49m[43mdecode_times[49m[43m,[49m
[1;32m    286[0m [43m        [49m[43mconcat_characters[49m[38;5;241;43m=[39;49m[43mconcat_characters[49m[43m,[49m
[1;32m    287[0m [43m        [49m[43mdecode_coords[49m[38;5;241;43m=[39;49m[43mdecode_coords[49m[43m,[49m
[1;32m    288[0m [43m        [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m    289[0m [43m        [49m[43muse_cftime[49m[38;5;241;43m=[39;49m[43muse_cftime[49m[43m,[49m
[1;32m    290[0m [43m        [49m[43mdecode_timedelta[49m[38;5;241;43m=[39;49m[43mdecode_timedelta[49m[43m,[49m
[1;32m    291[0m [43m    [49m[43m)[49m
[1;32m    292[0m [38;5;28;01mreturn[39;00m ds

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/store.py:24[0m, in [0;36mStoreBackendEntrypoint.open_dataset[0;34m(self, store, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta)[0m
[1;32m     12[0m [38;5;28;01mdef[39;00m [38;5;21mopen_dataset[39m(
[1;32m     13[0m     [38;5;28mself[39m,
[1;32m     14[0m     store,
[0;32m   (...)[0m
[1;32m     22[0m     decode_timedelta[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     23[0m ):
[0;32m---> 24[0m     [38;5;28mvars[39m, attrs [38;5;241m=[39m [43mstore[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43m)[49m
[1;32m     25[0m     encoding [38;5;241m=[39m store[38;5;241m.[39mget_encoding()
[1;32m     27[0m     [38;5;28mvars[39m, attrs, coord_names [38;5;241m=[39m conventions[38;5;241m.[39mdecode_cf_variables(
[1;32m     28[0m         [38;5;28mvars[39m,
[1;32m     29[0m         attrs,
[0;32m   (...)[0m
[1;32m     36[0m         decode_timedelta[38;5;241m=[39mdecode_timedelta,
[1;32m     37[0m     )

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/common.py:123[0m, in [0;36mAbstractDataStore.load[0;34m(self)[0m
[1;32m    101[0m [38;5;28;01mdef[39;00m [38;5;21mload[39m([38;5;28mself[39m):
[1;32m    102[0m     [38;5;124;03m"""[39;00m
[1;32m    103[0m [38;5;124;03m    This loads the variables and attributes simultaneously.[39;00m
[1;32m    104[0m [38;5;124;03m    A centralized loading function makes it easier to create[39;00m
[0;32m   (...)[0m
[1;32m    120[0m [38;5;124;03m    are requested, so care should be taken to make sure its fast.[39;00m
[1;32m    121[0m [38;5;124;03m    """[39;00m
[1;32m    122[0m     variables [38;5;241m=[39m FrozenDict(
[0;32m--> 123[0m         (_decode_variable_name(k), v) [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_variables[49m[43m([49m[43m)[49m[38;5;241m.[39mitems()
[1;32m    124[0m     )
[1;32m    125[0m     attributes [38;5;241m=[39m FrozenDict([38;5;28mself[39m[38;5;241m.[39mget_attrs())
[1;32m    126[0m     [38;5;28;01mreturn[39;00m variables, attributes

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/scipy_.py:171[0m, in [0;36mScipyDataStore.get_variables[0;34m(self)[0m
[1;32m    169[0m [38;5;28;01mdef[39;00m [38;5;21mget_variables[39m([38;5;28mself[39m):
[1;32m    170[0m     [38;5;28;01mreturn[39;00m FrozenDict(
[0;32m--> 171[0m         (k, [38;5;28mself[39m[38;5;241m.[39mopen_store_variable(k, v)) [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mds[49m[38;5;241m.[39mvariables[38;5;241m.[39mitems()
[1;32m    172[0m     )

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/scipy_.py:160[0m, in [0;36mScipyDataStore.ds[0;34m(self)[0m
[1;32m    158[0m [38;5;129m@property[39m
[1;32m    159[0m [38;5;28;01mdef[39;00m [38;5;21mds[39m([38;5;28mself[39m):
[0;32m--> 160[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_manager[49m[38;5;241;43m.[39;49m[43macquire[49m[43m([49m[43m)[49m

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/file_manager.py:181[0m, in [0;36mCachingFileManager.acquire[0;34m(self, needs_lock)[0m
[1;32m    166[0m [38;5;28;01mdef[39;00m [38;5;21macquire[39m([38;5;28mself[39m, needs_lock[38;5;241m=[39m[38;5;28;01mTrue[39;00m):
[1;32m    167[0m     [38;5;124;03m"""Acquire a file object from the manager.[39;00m
[1;32m    168[0m 
[1;32m    169[0m [38;5;124;03m    A new file is only opened if it has expired from the[39;00m
[0;32m   (...)[0m
[1;32m    179[0m [38;5;124;03m        An open file object, as returned by ``opener(*args, **kwargs)``.[39;00m
[1;32m    180[0m [38;5;124;03m    """[39;00m
[0;32m--> 181[0m     file, _ [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_acquire_with_cache_info[49m[43m([49m[43mneeds_lock[49m[43m)[49m
[1;32m    182[0m     [38;5;28;01mreturn[39;00m file

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/file_manager.py:205[0m, in [0;36mCachingFileManager._acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    203[0m     kwargs [38;5;241m=[39m kwargs[38;5;241m.[39mcopy()
[1;32m    204[0m     kwargs[[38;5;124m"[39m[38;5;124mmode[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_mode
[0;32m--> 205[0m file [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_opener[49m[43m([49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_args[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    206[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_mode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m:
[1;32m    207[0m     [38;5;66;03m# ensure file doesn't get overridden when opened again[39;00m
[1;32m    208[0m     [38;5;28mself[39m[38;5;241m.[39m_mode [38;5;241m=[39m [38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/xarray/backends/scipy_.py:99[0m, in [0;36m_open_scipy_netcdf[0;34m(filename, mode, mmap, version)[0m
[1;32m     96[0m     filename [38;5;241m=[39m io[38;5;241m.[39mBytesIO(filename)
[1;32m     98[0m [38;5;28;01mtry[39;00m:
[0;32m---> 99[0m     [38;5;28;01mreturn[39;00m [43mscipy[49m[38;5;241;43m.[39;49m[43mio[49m[38;5;241;43m.[39;49m[43mnetcdf_file[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m,[49m[43m [49m[43mmmap[49m[38;5;241;43m=[39;49m[43mmmap[49m[43m,[49m[43m [49m[43mversion[49m[38;5;241;43m=[39;49m[43mversion[49m[43m)[49m
[1;32m    100[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m [38;5;28;01mas[39;00m e:  [38;5;66;03m# netcdf3 message is obscure in this case[39;00m
[1;32m    101[0m     errmsg [38;5;241m=[39m e[38;5;241m.[39margs[[38;5;241m0[39m]

File [0;32m~/miniconda3/envs/mynewbook/lib/python3.10/site-packages/scipy/io/_netcdf.py:245[0m, in [0;36mnetcdf_file.__init__[0;34m(self, filename, mode, mmap, version, maskandscale)[0m
[1;32m    243[0m [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m filename
[1;32m    244[0m omode [38;5;241m=[39m [38;5;124m'[39m[38;5;124mr+[39m[38;5;124m'[39m [38;5;28;01mif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124ma[39m[38;5;124m'[39m [38;5;28;01melse[39;00m mode
[0;32m--> 245[0m [38;5;28mself[39m[38;5;241m.[39mfp [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;132;43;01m%s[39;49;00m[38;5;124;43mb[39;49m[38;5;124;43m'[39;49m[43m [49m[38;5;241;43m%[39;49m[43m [49m[43momode[49m[43m)[49m
[1;32m    246[0m [38;5;28;01mif[39;00m mmap [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    247[0m     [38;5;66;03m# Mmapped files on PyPy cannot be usually closed[39;00m
[1;32m    248[0m     [38;5;66;03m# before the GC runs, so it's better to use mmap=False[39;00m
[1;32m    249[0m     [38;5;66;03m# as the default.[39;00m
[1;32m    250[0m     mmap [38;5;241m=[39m ([38;5;129;01mnot[39;00m IS_PYPY)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_image_pair/landsat/v02/N20E080/LC08_L1TP_142040_20191228_20200824_02_T1_X_LC08_L1TP_142040_20200113_20200823_02_T1_G0120V02_P098.nc'
FileNotFoundError: [Errno 2] No such file or directory: 'http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_image_pair/landsat/v02/N20E080/LC08_L1TP_142040_20191228_20200824_02_T1_X_LC08_L1TP_142040_20200113_20200823_02_T1_G0120V02_P098.nc'

